### ISSUE TITLE
multiple contributors

### ISSUE THREAD

**Issue by millertg** [VandyVRC/srophe-eXist-app#134]
@wsalesky @shubenda 
Can we fix the authorial display so that we avoid singular nouns?

For example: 
Entry Title: 扶壁栱 fúbìgǒng

Authorial and Editorial Responsibility:
Tracy Miller, editor, Architectura Sinica
**REN Sijie 任思捷, and YANG Wantian, entry contributor, “ 扶壁栱 fúbìgǒng”**

Is it possible to have the one in bold displayed as below to avoid singular and plural problem?
REN Sijie 任思捷,  entry contributor
YANG Wantian, entry contributor

**Comment by wsalesky** [comment]
@millertg  Yes, I will take a look. We could also add an s to the first version when there is more than 1 contributor. Let me know your preference.

**Comment by millertg** [comment]
@wsalesky @shubenda 
That would be great! I like displaying fewer lines.

**Comment by wsalesky** [comment]
Fixed.

**Comment by millertg** [comment]
I am still seeing "contributor" as singular in fubigong
https://architecturasinica.org/keyword/k000029
do you see "contributors"?

**Comment by shubenda** [comment]
I saw contributor as singular too.

Yuh-Fen

**Comment by wsalesky** [comment]
Sorry this should be fixed now.
